### PR TITLE
Extension the support for platforms consisting of arbitrary numbers of GRID storages and workers

### PR DESCRIPTION
**Pull request by HerrHorizontal**
This PR extends the simulator to support arbitrary big platforms with arbitrary numbers of GRID storages and workers.

It implements a way to define the roles of certain hosts via a tag in the XML platform description, and reachable caches can be identified in the same network zone and child zones. 
Furthermore, it implements a switch to turn caching on and off.
Last, the duplication of jobs has been fixed and the monitoring improved.

### CODE REVIEW

**Comment by HerrHorizontal** [comment]
I think this is now ready for merging. I also suggest making a new release out of this.

**Comment by HerrHorizontal** [comment]
@henricasanova I am also considering fixing the WRENCH dependency to [v2.0](https://github.com/wrench-project/wrench/releases/tag/v2.0). Or do you think there are any recent developments, which should be included on top?

**Comment by HerrHorizontal** [comment]
@henricasanova you are right, it does not compile with WRENCH v.2.0 but only on the master. I think I can fix the WRENCH dependency onto the latest commit on master. Or do you think I should wait for pending changes in WRENCH?

**Comment by henricasanova** [comment]
@HerrHorizontal  I am not expecting any commits of significance upcoming in WRENCH. So the master as of today is fine.

**Review by ArturAkh — APPROVED** [review]
Looks good, thanks!

**Review by HerrHorizontal — COMMENTED** [review]
Checked and concluded that it is ready to go.

**Pull request merged**
