### PR TITLE
Extend the workload generation to enable a timeshift in the job submit

### PR DESCRIPTION
**Pull request by HerrHorizontal**
In order to be able to simulate jobs submitted at different times, a time offset at execution controller (taking care of workload execution) start is introduced. 
For the interface to the configuration of the workloads a new `Workload` class is introduced, which contains a collection of `JobSpecification`s, the submission-time offset and the type of workload and the functions for creation. The workload type replaces the workload type in the job specification.

### CODE REVIEW

**Comment by HerrHorizontal** [comment]
I have tested the new functionality and everything works just fine. I don't see any significant slowing down in execution of the simulation.

**Comment by HerrHorizontal** [comment]
@henricasanova could you have a look into the code changes? I think it is fine, but maybe you spot some bad style, which could be improved.

**Comment by henricasanova** [comment]
This looks good to me. I don't see anything problematic. In standard language about scheduling, instead of "time_offset" people would likely instead have "arrival_date" or "arrival_time". But of course that doesn't matter at all. All looks good to me.

**Review by henricasanova — APPROVED** [review]

**Comment by HerrHorizontal** [comment]
> This looks good to me. I don't see anything problematic. In standard language about scheduling, instead of "time_offset" people would likely instead have "arrival_date" or "arrival_time". But of course that doesn't matter at all. All looks good to me.

I have changed the wording. Thanks for this comment. Such things might not change the outcome, but increase the readability for users used to different vocabulary I use as a layman.

**Comment by HerrHorizontal** [comment]
> This looks good to me. I don't see anything problematic. In standard language about scheduling, instead of "time_offset" people would likely instead have "arrival_date" or "arrival_time". But of course that doesn't matter at all. All looks good to me.

I have changed the wording. Thanks for this comment. Such things might not change the outcome, but increase the readability for users used to different vocabulary I use as a layman.

**Comment by HerrHorizontal** [comment]
I have tested the effect of the changes on the validation simulation. It seems that there is an minor impact:
Looking at the old (main branch) simulation:
hitrateWalltime_fullstreamjobs_1G_old
and comparing it to the new one (this branch):
hitrateWalltime_fullstreamjobs_1G
it seems there are some minimal changes in the observed distributions.
I have no idea where it comes from. Actually I wouldn't expect any influence by the introduced changes on the jobs' executions. @henricasanova do you have an idea?

**Comment by HerrHorizontal** [comment]
I compared it again to the validation data I gathered. And actually it seems it is now slightly more compatible with the data. Nonetheless, the differences are far away from being significant. I conclude, it can be merged, then.

**Pull request merged**
